# Generated by Django 5.0.7 on 2024-07-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_career"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="preview_image",
            field=models.ImageField(default="", upload_to="media/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="short_description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
