# Generated by Django 5.0.7 on 2024-07-27 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_blog_preview_image_blog_short_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="author",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="projects.blog",
                    ),
                ),
            ],
        ),
    ]
