# Generated by Django 5.0.7 on 2024-09-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_remove_project_image_project_status_projectimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="preview_image",
            field=models.ImageField(default="", upload_to="media/"),
            preserve_default=False,
        ),
    ]
