# Generated by Django 5.0.7 on 2024-09-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_project_preview_image_alter_projectimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="preview_image",
            field=models.ImageField(upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
