# Generated by Django 5.0.7 on 2024-09-12 02:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_alter_project_preview_image_alter_projectimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="author",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.DeleteModel(
            name="ProjectImage",
        ),
    ]
