# Generated by Django 5.0.7 on 2024-10-05 12:35

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_project_author_alter_project_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=django_quill.fields.QuillField(),
        ),
    ]
