# Generated by Django 5.0.7 on 2025-05-11 21:50

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_blog_content_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
